import test from 'node:test';
import assert from 'node:assert/strict';
import RAPIER from '@dimforge/rapier3d-compat';
import { createRagdoll, activateRagdoll } from '../src/ragdoll.js';
await RAPIER.init();
function setup(){const world=new RAPIER.World({x:0,y:-9.8,z:0});world.numSolverIterations=12;world.timestep=1/120;world.createCollider(RAPIER.ColliderDesc.cuboid(20,.5,20).setTranslation(0,-.5,0).setFriction(.75));return world;}
function anchorError(j){const a=j.body1(),b=j.body2();function transform(body,v){const q=body.rotation(),p=body.translation();const uv={x:q.y*v.z-q.z*v.y,y:q.z*v.x-q.x*v.z,z:q.x*v.y-q.y*v.x};const uuv={x:q.y*uv.z-q.z*uv.y,y:q.z*uv.x-q.x*uv.z,z:q.x*uv.y-q.y*uv.x};return {x:p.x+v.x+2*(q.w*uv.x+uuv.x),y:p.y+v.y+2*(q.w*uv.y+uuv.y),z:p.z+v.z+2*(q.w*uv.z+uuv.z)};}const a1=transform(a,j.anchor1()),a2=transform(b,j.anchor2());return Math.hypot(a1.x-a2.x,a1.y-a2.y,a1.z-a2.z);}
test('standing characters stay still without oscillating springs',()=>{const world=setup();const p=createRagdoll(world,0,0);for(let i=0;i<1200;i++)world.step();for(const part of p.parts){const pos=part.body.translation();assert.ok(Math.abs(pos.y-part.spec.pos[1])<1e-5);assert.equal(part.body.linvel().y,0);}assert.ok(p.parts.reduce((sum,o)=>sum+o.body.mass(),0)>65);world.free();});
test('impacted ragdolls stay connected and settle without explosive motion',()=>{for(const location of ['torso','head','forearm1','shin-1']){const world=setup();const p=createRagdoll(world,0,0);activateRagdoll(p);const hit=p.parts.find(o=>o.spec.name===location);hit.body.applyImpulseAtPoint({x:1,y:0,z:-12},hit.body.translation(),true);assert.ok(hit.body.linvel().z<-.1,'Impact impulse was ignored');let maxSpeed=0,maxError=0;for(let i=0;i<1800;i++){world.step();for(const part of p.parts){const pos=part.body.translation(),v=part.body.linvel();assert.ok(Number.isFinite(pos.y));assert.ok(pos.y>-.15,'body tunnels through floor');maxSpeed=Math.max(maxSpeed,Math.hypot(v.x,v.y,v.z));}for(const j of p.joints)maxError=Math.max(maxError,anchorError(j));}assert.ok(maxSpeed<15,`${location}: speed ${maxSpeed}`);assert.ok(maxError<.08,`${location}: anchor error ${maxError}`);assert.ok(p.torso.body.translation().y<.5,'torso did not settle');const speeds=p.parts.map(o=>{const v=o.body.linvel();return Math.hypot(v.x,v.y,v.z);});assert.ok(Math.max(...speeds)<.2,`${location}: still jittering ${Math.max(...speeds)}`);console.log(location,{maxSpeed,maxError});world.free();}});
test('separate ragdolls collide while each excludes its own colliders',()=>{const world=setup();const a=createRagdoll(world,-.6,0,0),b=createRagdoll(world,.6,0,1);assert.notEqual(a.parts[0].body.collider(0).collisionGroups(),b.parts[0].body.collider(0).collisionGroups());activateRagdoll(a);activateRagdoll(b);a.torso.body.applyImpulse({x:30,y:0,z:0},true);b.torso.body.applyImpulse({x:-30,y:0,z:0},true);for(let i=0;i<1200;i++)world.step();for(const p of [a,b])for(const o of p.parts){assert.ok(Number.isFinite(o.body.translation().x));assert.ok(anchorError(p.joints[0])<.08);}world.free();});
