import test from 'node:test';
import assert from 'node:assert/strict';
import RAPIER from '@dimforge/rapier3d-compat';
import {createRagdoll,activateRagdoll} from '../src/ragdoll.js';
import {registerHit,stepReaction,stepWounds} from '../src/reactions.js';
await RAPIER.init();
const random=()=>.5,dt=1/120;
function setup(){const w=new RAPIER.World({x:0,y:-9.8,z:0});w.timestep=dt;w.numSolverIterations=12;w.createCollider(RAPIER.ColliderDesc.cuboid(20,.5,20).setTranslation(0,-.5,0));return w;}
function run(w,p,seconds,observe=()=>{}){for(let i=0;i<seconds*120;i++){stepReaction(p,dt,false);w.step();observe(i,p);}}
function speed(o){const v=o.body.linvel();return Math.hypot(v.x,v.y,v.z);}
test('surviving characters visibly move well after the initial hit instead of freezing',()=>{const w=setup(),p=createRagdoll(w,0,0);activateRagdoll(p);registerHit(p,p.torso,{x:0,y:0,z:.2},.16,random);p.torso.body.applyImpulse({x:0,y:0,z:-12},true);let maxSpeed=0;const samples=[];run(w,p,20,i=>{for(const o of p.parts){maxSpeed=Math.max(maxSpeed,speed(o));const pos=o.body.translation();assert.ok(Number.isFinite(pos.x)&&pos.y>-.15);}if(i>600&&i%60===0)samples.push(p.parts.find(o=>o.spec.name==='forearm1').body.translation());});assert.ok(maxSpeed<12);const movement=Math.max(...samples.map(a=>Math.hypot(a.x-samples[0].x,a.y-samples[0].y,a.z-samples[0].z)));assert.ok(movement>.08,`late reaction movement only ${movement}m`);assert.equal(p.state,'guarding');assert.ok(p.parts.every(o=>!o.body.isSleeping()));assert.ok(p.torso.body.translation().y>1.1,'one mild torso hit knocked character down');console.log('late forearm displacement:',movement);w.free();});
test('repeated hits wake sleeping characters without cancelling existing momentum',()=>{const w=setup(),p=createRagdoll(w,0,0);activateRagdoll(p);run(w,p,4);p.parts.forEach(o=>o.body.sleep());assert.ok(p.torso.body.isSleeping());registerHit(p,p.torso,{x:0,y:0,z:.2},.16,random);assert.ok(p.parts.every(o=>!o.body.isSleeping()));p.torso.body.setLinvel({x:1,y:0,z:0},true);registerHit(p,p.parts.find(o=>o.spec.name==='shin1'),{x:0,y:0,z:0},.1,random);activateRagdoll(p);assert.equal(p.hitCount,2);assert.equal(p.lastHit,'shin1');assert.equal(p.torso.body.linvel().x,1);assert.ok(p.vitality>.7);w.free();});
test('unresponsive bodies lose voluntary motor force and settle normally',()=>{const w=setup(),p=createRagdoll(w,0,0);activateRagdoll(p);registerHit(p,p.torso,{x:0,y:0,z:.2},1,random);p.torso.body.applyImpulse({x:0,y:0,z:-12},true);run(w,p,40);assert.equal(p.state,'unresponsive');assert.ok(p.parts.every(o=>speed(o)<.1));assert.ok(p.parts.every(o=>{const v=o.body.angvel();return Math.hypot(v.x,v.y,v.z)<.1;}));assert.ok(p.parts.some(o=>o.body.isSleeping()));w.free();});
test('grabbing suppresses voluntary motion; releasing restores survivor reactions',()=>{const w=setup(),p=createRagdoll(w,0,0);activateRagdoll(p);registerHit(p,p.torso,{x:0,y:0,z:.2},.1,random);stepReaction(p,dt,true);assert.equal(p.state,'held');stepReaction(p,dt,false);assert.equal(p.state,'staggering');run(w,p,3);assert.equal(p.state,'guarding');w.free();});
test('nearby pellet hits merge wounds, emission pauses, and all wounds eventually expire',()=>{const w=setup(),p=createRagdoll(w,0,0);for(let i=0;i<10;i++)registerHit(p,p.torso,{x:0,y:0,z:.2},.1,random);assert.equal(p.wounds.length,1);let emitted=0;for(let i=0;i<30;i++)stepWounds(p,0,()=>emitted++,random);assert.equal(emitted,0);stepWounds(p,.5,()=>emitted++,random);assert.equal(emitted,1);stepWounds(p,.01,()=>emitted++,random);assert.equal(emitted,1);for(let i=0;i<4800;i++)stepWounds(p,dt,()=>emitted++,random);assert.equal(p.wounds.length,0);assert.ok(emitted>20&&emitted<80);assert.equal(p.vitality,0);w.free();});
test('standing idle shifts are coherent and do not drift or accumulate',()=>{const w=setup(),p=createRagdoll(w,0,0);run(w,p,60);for(const o of p.parts){const v=o.body.translation();assert.ok(Math.hypot(v.x-o.spec.pos[0],v.y-o.spec.pos[1],v.z-o.spec.pos[2])<.02);}assert.equal(p.state,'idle');w.free();});

test('multiple injured characters stay stable through collisions and repeated limb impacts',()=>{const w=setup();const people=Array.from({length:6},(_,i)=>createRagdoll(w,(i%3)*1.1,Math.floor(i/3)*1.1));let maxSpeed=0;for(let frame=0;frame<1500;frame++){if(frame%90===0){const p=people[Math.floor(frame/90)%people.length],part=p.parts[3+Math.floor(frame/90)%8];activateRagdoll(p);registerHit(p,part,{x:0,y:0,z:0},.16,random);part.body.applyImpulse({x:1,y:0,z:-Math.min(12,part.body.mass()*3)},true);}for(const p of people){stepReaction(p,dt);stepWounds(p,dt,()=>{},random);}w.step();for(const p of people)for(const o of p.parts){const pos=o.body.translation();assert.ok(Number.isFinite(pos.x)&&pos.y>-.15);maxSpeed=Math.max(maxSpeed,speed(o));}}assert.ok(maxSpeed<16,`unstable crowded-body speed ${maxSpeed}`);assert.ok(people.every(p=>p.hitCount>=2));w.free();});

test('neck stays within its hard limits during off-centre head impacts',()=>{const w=setup(),p=createRagdoll(w,0,0);activateRagdoll(p);const head=p.parts.find(o=>o.spec.name==='head');registerHit(p,head,{x:0,y:.1,z:0},.48,random);head.body.applyImpulseAtPoint({x:0,y:0,z:-12},{x:0,y:2,z:.1},true);let maxAngle=0;run(w,p,10,()=>{const a=p.torso.body.rotation(),b=head.body.rotation();const dot=Math.abs(a.x*b.x+a.y*b.y+a.z*b.z+a.w*b.w);const angle=2*Math.acos(Math.min(1,dot));maxAngle=Math.max(maxAngle,angle);});assert.ok(maxAngle<.5,`neck exceeded safe range: ${maxAngle}`);w.free();});

test('leg injury disables balance and grounded survivor visibly struggles',()=>{const w=setup(),p=createRagdoll(w,0,0);activateRagdoll(p);const leg=p.parts.find(o=>o.spec.name==='shin1');registerHit(p,leg,{x:0,y:0,z:0},.25,random);leg.body.applyImpulse({x:0,y:0,z:-5},true);const positions=[];run(w,p,15,i=>{if(i>600&&i%30===0)positions.push(p.parts.find(o=>o.spec.name==='forearm-1').body.translation());});assert.equal(p.standing,false);assert.ok(p.torso.body.translation().y<.5);const movement=Math.max(...positions.map(v=>Math.hypot(v.x-positions[0].x,v.y-positions[0].y,v.z-positions[0].z)));assert.ok(movement>.08,`no visible grounded struggle: ${movement}`);w.free();});
